Software/src/SettingsWindow.cpp
=> Fix crash on profile deletion

Software/src/GrabManager.cpp, Software/src/GrabManager.hpp
=> No grab update

Software/grab/D3D10Grabber.cpp, Software/grab/WinUtils.cpp, Software/src/ApiServer.cpp, Software/src/ApiServer.hpp, Software/src/LedDeviceManager.cpp, Software/src/LightpackApplication.cpp, Software/src/LightpackApplication.hpp
=> Move D3D10Grabber to dedicated thread

README.md, Software/scripts/linux/prepare_installer.sh
=> Update binary path in linux script, include locale generation in README

Software/grab/D3D10Grabber.cpp
=> DX scanning

Software/grab/grab.pro, Software/src/src.pro
This should allow to compile the project with Clang and GCC.
PTAL.
=> Enable C++11 mode for GCC and Clang.

Software/src/LightpackApplication.cpp
create a build to test curren trayicon stauts
=> Remove appmenu trayicon workaround

.travis.yml
=> Dreamer dead psieg upstream avoid memmove for image data

README.md
I fixed the markdown issues, capitalized all titles and cleaned up some of the numbering and grammar.
=> Markdown Fix

Software/src/LedDeviceAdalight.hpp, Software/src/Settings.cpp, Software/src/enums.hpp, Software/src/wizard/ZonePlacementPage.ui
a few modification needed to get more than 255 leds. 
Maximum number set is 511
=> more than 255 led strip

.gitmodules, .travis.yml, Software/dist_windows/script.iss, Software/scripts/win32/build_UpdateElevate.bat, Software/scripts/win32/prepare_installer.sh, Software/scripts/win32/wipe.sh, Software/src/Settings.cpp, Software/src/Settings.hpp, Software/src/SettingsDefaults.hpp, Software/src/SettingsWindow.cpp, Software/src/SettingsWindow.hpp, Software/src/SettingsWindow.ui, Software/src/UpdatesProcessor.cpp, Software/src/UpdatesProcessor.hpp, Software/src/src.pro, Software/src/systrayicon/SysTrayIcon.hpp, Software/src/systrayicon/SysTrayIcon_qt_p.hpp, Software/src/version.h
Downloads and runs updates packages using UpdateElevate.
UpdateElevate provides elevation to binaries accompanied by a valid digital signature.
=> Automatic selfupdater

Software/src/GrabManager.cpp
=>  Try to restore original grab area positions when screen layout changes

Software/src/LedDeviceLightpack.cpp, Software/src/LedDeviceManager.cpp, Software/src/LedDeviceManager.hpp
=> Try to reconnect the device after IO errors

.gitignore, Software/src/LightpackApplication.cpp, Software/src/SessionChangeDetector.cpp, Software/src/SessionChangeDetector.hpp, Software/src/SettingsWindow.ui
I paired it with session sleep/resume
=> display sleep support (windows)

Software/grab/calculations.cpp
Clean version of #215: added some consts and macros for clarity
=> grab calculations: replaced 4 accumulate... functions with 1 templated,

.gitignore, README.md, Software/scripts/macos/generate_xcode_project.sh
I don't know if there's a better way to add grab/math as dependencies to Prismatik but it works for now...
=> macOS Xcode script

.gitignore, Software/grab/calculations.cpp, Software/scripts/macos/generate_xcode_project.sh, Software/src/main.cpp
Small things here and there.
And an ugly hack to circumvent qmake's [unfixed limitation](https://bugreports.qt.io/browse/QTBUG-54791). This is for Xcode only though, so it won't break CI builds.
=> macos deprecations

Software/math/PrismatikMath.cpp, Software/math/include/PrismatikMath.hpp, Software/src/SettingsWindow.cpp
labels switch between black and white depending on background color
=> high contrast virtual led labels

README.md, Software/build-vars.prf.default, Software/src/PulseAudioSoundManager.cpp, Software/src/PulseAudioSoundManager.hpp, Software/src/SoundManagerBase.cpp, Software/src/src.pro
To Whom It May Concern
Tries to add Pulseaudio support for soundviz. Adds libpulse and FFTW3 dependency.
This pull request is primarily just to get more eyes on this for testing.
=> Pulseaudio

Software/grab/MacOSAVGrabber.mm
It seems like the scaling issue documented in the comments still exists on macOS 10.14, so scaling down to 5% isn't safe, sadly. At least until we can reliably determine what configurations have the scaling bug.
Additionally, in some other cases, 5% scale performed way worse than larger ones.
And 5% is a bit small for big LED densities.
So leaving this at 20% for now.
=> mac av grabber safer scale

Software/src/LedDeviceManager.cpp, Software/src/LedDeviceManager.hpp, Software/src/LightpackApplication.cpp, Software/src/MoodLampManager.cpp
=> startup frames

.travis.yml
=> travis: xcode12.2

Software/grab/MacUtils.mm
should fix post-dither-rollback flicker in #399 and in original #326
=> macOS gamma LUT index fix

Software/src/LogWriter.cpp, Software/src/LogWriter.hpp, Software/src/SettingsWindow.cpp, Software/src/main.cpp
and set logs dir to logwriter even in disabled state to be able to open it
=> enable open logs button when folder exists

Software/src/LightpackApplication.cpp, Software/src/LightpackApplication.hpp
it just silently does nothing otherwise
=> lightpack application: show warnings in nogui mode when receiving messages

Software/res/LightpackResources.qrc, Software/src/GrabConfigWidget.cpp, Software/src/GrabWidget.cpp, Software/src/GrabWidget.hpp, Software/src/wizard/ConfigureUdpDevicePage.cpp, Software/src/wizard/GlobalColorCoefPage.cpp, Software/src/wizard/WizardPageUsingDevice.cpp, Software/src/wizard/WizardPageUsingDevice.hpp, Software/src/wizard/ZonePlacementPage.cpp, Software/src/wizard/ZonePlacementPage.hpp
=> housekeeping 2

Software/build-config.prf, Software/build-vars.prf.default, Software/src/LogWriter.cpp, Software/src/hidapi/mac/hid.c, Software/src/qtsingleapplication/src/qtsingleapplication.cpp
official 6.2 beta finally seems to have serialport and arm64
the remaining blocker is in `UpdatesProcessor.cpp`, I leave that to you
=> qt6 housekeeping

Software/res/LightpackResources.qrc, Software/res/translations/en.ts, Software/res/translations/pl_PL.ts, Software/res/translations/ru_RU.ts, Software/res/translations/uk_UA.ts, Software/src/SettingsWindow.ui, Software/src/src.pro, Software/src/wizard/LightpackDiscoveryPage.cpp
Mainly added Polish UI translation.
Updated one file to use correct plural messages, as in Polish it actually matters.
Added english translation files as well, although the only translation inside is the corect plural form for English.
=> Added Polish translation.

Software/res/translations/zh-cn.ts
Added simplified Chinese translation for zh-cn.ts，In order to better promote in the Chinese community.
=> Added simplified Chinese translation for zh-cn.ts
