psieg/Lightpack

Software/src/LightpackApplication.cpp
Software/src/LightpackCommandLineParser.cpp
Software/src/LightpackCommandLineParser.hpp
Software/src/src.pro
Software/tests/LightpackCommandLineParserTest.cpp
Software/tests/LightpackCommandLineParserTest.hpp
Software/tests/TestsMain.cpp
Software/tests/tests.pro

Hi!
Here is a part of my fork, it does the following things:
- Add alternate way to set debug level (--debug=level).
- Handle --help and --version command switches.
- Add unit-tests for LightpackCommandLineParser class.
Also I enabled C++11 mode for tests.
PTAL.

Implement LightpackCommandLineParser class.

---

Software/src/systrayicon/SysTrayIcon_qt_p.hpp

This isn't ready for merging, as this will probably mess things up for everyone not on a Retina Mac, but I wanted to show how to provide Retina icons here.
Fixes #96

Make menubar icon Retina ready on macOS

---

Software/grab/GrabberBase.cpp
Software/grab/MacOSGrabber.cpp
Software/grab/include/GrabberBase.hpp
Software/grab/include/MacOSGrabber.hpp

Hi.
Here is copy of PR in my own fork of Lightpack, https://github.com/dreamer-dead/MyLightpack/pull/2
I added one commit from my master branch except that to prettify MacOS grabber code.
Before applying this patch default profiler for Mac(Instruments) tells me that intrinsic memove() call eats about 80% of all CPU consumed by the Prismatic app even in Release configuration (https://yadi.sk/i/1AS6f0eDuZr8n). That's why I tried to remove it.
Please, take a look at this PR.
Note, that Mac build seems broken on my machine with Qt5.5 and Clang compiler due to missing flags `QMAKE_CXXFLAGS += -std=c++11 -stdlib=libc++`. MSVS enables C++1x mode by default.

Get rid of unnecessary memmove() for MacOS.

---

Software/src/wizard/GlobalColorCoefPage.ui

I finally got around to installing the latest release and spotted a typo in the white balance description: "lateron" rather than "later on".
Other than that the new white balance page looks _awesome_! Nice work!

Fixed typo in white balance description

---

Software/apiexamples/pyLightpack/lightpack.py
Software/apiexamples/pyLightpack/testall.py

I updated the Python API library:
- Added `getLeds` and `getLedMap` functions to automatically update the LED list from Prismatik.
- Added `setFrame` function to push an entire frame of color data to the LEDs.
- `_ledMap` now has a default in the constructor, as the map is updated automatically from Prismatik.
- Encoded API key for using key authorized API in Python 3.
- LED count is now returned as an integer.
- Moved string decoding to `__readResult()` function, which should also fix the few functions that were missing it.
- Added range check to `setColor` which should prevent accidentally writing to the n-1 LED in place of 0.
I also cleaned up the whitespace and modified the `testall.py` example to index at 1 (#143) I tested this with Python 2.7 and 3.6.

Updated Python API

---

Software/src/wizard/ConfigureDevicePage.cpp
Software/src/wizard/GlobalColorCoefPage.cpp

The configuration page wasn't reading current settings to prefill baud rate / serial port / color sequence, so you had to redo those manually every time.
And for RGB coefs, I switched to the actual maximum value of the UI element to scale them before reading from / saving to settings instead of hardcoded values.

small fixes to device configuration page

---

Software/src/wizard/ConfigureDevicePage.ui

In the setup wizard, the baud rate warning text can be vertically truncated by resizing the window. This PR sets a minimum size and aligns it so it's always visible.

Baud Rate Warning Text Fix

---

Software/build-vars.prf.default
Software/src/GrabManager.cpp
Software/src/GrabManager.hpp
Software/src/src.pro

Clone of #214:
I think we are ok to try building this.
I did the qmake bits (`build-vars` and `src.pro`) and `GrabManager`'s `#ifdefs`.
I [re-released](https://github.com/zomfg/NightLightLibrary/releases/tag/v1.1) NightLight library without external includes and with debug/release builds.
I'm able to build first try after (re-)generating the `sln` (but my VS knows about bond and boost so that's the doubt I have at the moment).
Now, as you can see this branch too, has a ton of stray merge commits, this dates from a while ago and it's based on the color-temperature branch that had them, sorry :(
Files of interest are:
- `src/src.pro`
- `src/GrabManager.[ch]pp`
- `build-vars.prf.default`
- `src/SettingsWindow.ui` (help text)

night light support (clean)

---

Software/src/wizard/Wizard.ui

The UI elements are bigger than on Windows so some parts are squished (especially White Coef page)
And just in case: there seems to be an issue on Qt's side with dark mode
https://bugreports.qt.io/browse/QTBUG-71696
The rest of the app looks good though.

macos device wizard dimensions

---

Software/grab/GrabberBase.cpp
Software/grab/MacOSGrabber.cpp
Software/grab/include/GrabberBase.hpp

Current macOS grabber uses the raw image buffer without cropping to the actual width, so in some conditions `(width * bytesPerPixel) != bytesPerRow` so `Calculations::calculateAvgColor` is looping out of alignment and returning wrong colors, `GrabbedScreen.bytesPerRow` override fixes this and adds a tiny performance boost thanks to the proper memory alignment.
#79 In HiDPI situations screen dimensions and coords are scaled to whatever, but the image is at full size so widget rects are misplaced when passed to `Calculations::calculateAvgColor`. Using `pixelRatio` as `GrabbedScreen.scale` to resize rects fixes this...
...and increases the performance hit!...or actually brings to what it should've been. I'm thinking maybe we can pass `pixelRatio` to `Calculations::calculateAvgColor` and use …

macos cg grabber fix

---

Software/src/LightpackApplication.cpp
Software/src/MacOSSoundManager.mm
Software/src/Settings.cpp
Software/src/Settings.hpp
Software/src/SettingsWindow.cpp
Software/src/SettingsWindow.hpp
Software/src/SettingsWindow.ui
Software/src/SoundManagerBase.cpp
Software/src/SoundManagerBase.hpp
Software/src/SoundVisualizer.cpp
Software/src/SoundVisualizer.hpp
Software/src/WindowsSoundManager.cpp
Software/src/src.pro

just some fun stuff..
the objective was to extract the visualization part from `SoundManager` into its own class
...and while at it, make it simple to add other variants: all you have to do is copy an existing declaration in `SoundVisualizer.cpp` and change name and content to your taste and it should magically appear in the list on the soundviz page

soundviz types

---

Software/math/include/PrismatikMath.hpp
Software/src/LightpackApplication.cpp
Software/src/LiquidColorGenerator.cpp
Software/src/LiquidColorGenerator.hpp
Software/src/MoodLamp.cpp
Software/src/MoodLamp.hpp
Software/src/MoodLampManager.cpp
Software/src/MoodLampManager.hpp
Software/src/Settings.cpp
Software/src/Settings.hpp
Software/src/SettingsDefaults.hpp
Software/src/SettingsWindow.cpp
Software/src/SettingsWindow.hpp
Software/src/SettingsWindow.ui
Software/src/src.pro

In a similar fashion to SoundViz selector, here are some (animated) mood lamps...
Notable change to `MoodLampManager`: the update rate is now managed by lamps and not by `LiquidColorGenerator`, each lamp can have it's own framerate if required so by the desired animation (I used 33ms/30fps as default).
Other (small but) notable change: as per [Qt doc](http://doc.qt.io/qt-5/qtglobal-obsolete.html#qrand), I replaced `(s)qrand` with `QRandomGenerator`, and since it was used only in `LiquidColorGenerator` I removed it from `PrismatikMath` and used directly as a member.
There is one issue that is also present on the `master`: when you quit Prismatik with static color mood lamp on and relaunch, it doesn't turn on unless you switch modes (or, now, lamps).
It looks like some kind of race …

mood lamps

---

Software/src/MoodLamp.cpp

clang did not like it, was refusing to build

Mood Lamps: removed "static" from const member vars

---

Software/src/LedDeviceAdalight.cpp
Software/src/LedDeviceArdulight.cpp

...and while I was there I removed `QIODevice::Unbuffered` which is [unsupported ](https://doc.qt.io/qt-5/qserialport.html#open)by `open()` and the first call is always failing
https://github.com/psieg/Lightpack/blob/a8b05af871aed0153dcfb5b2f292cacf189230fc/Software/src/LedDeviceAdalight.cpp#L202-L213
So I'm not sure if the subsequent retry is still needed and if it was caused by something similar while 10.04 was around like the comment mentions. But Ardulight does not have `QIODevice::Unbuffered` and still has the retry, so I left the other one too.

more verbose serial error log

---

Software/src/LedDeviceManager.cpp

matching  `connect()`
https://github.com/psieg/Lightpack/blob/a8b05af871aed0153dcfb5b2f292cacf189230fc/Software/src/LedDeviceManager.cpp#L497

led device manager: wrong led device WBA update slot

---

Software/math/PrismatikMath.cpp
Software/math/include/PrismatikMath.hpp
Software/src/GrabManager.cpp
Software/src/LightpackApplication.cpp
Software/src/MoodLampManager.cpp
Software/src/MoodLampManager.hpp
Software/src/SettingsWindow.cpp
Software/src/SettingsWindow.hpp
Software/src/SoundManagerBase.cpp
Software/src/SoundManagerBase.hpp

People using low baud rates with long strips seems to be a recurring issue, hopefully this will help them troubleshoot.
I used [this formula](https://www.partsnotincluded.com/calculating-adalight-framerate-limits/) to get an estimate for current configuration max and when FPS goes over it FPS counter becomes red and shows "LOW BAUDRATE". This is for Adalight/Ardulight only.
Also, since mood lamps and soundviz are animated, I made them report their FPS so they can trigger the same warning. I removed " / MAX" part for these modes since the MAX is based on grab interval.
And lastly, I set grab fps timer to a `PreciseTimer` to get more accurate readings.
Edit: if travis can be bumped to `osx_image: xcode11.3`, that'd be great :)

Show "low baudrate" warning

---

Software/src/LedDeviceAdalight.cpp
Software/src/LedDeviceAdalight.hpp
Software/src/LedDeviceArdulight.cpp
Software/src/LedDeviceArdulight.hpp

While searching for that mystery leak (#308) I took a look at the edge case where the baud rate is so low that the serial buffer doesn't have enough time to be emptied: the frames pile up and cause massive lag (and the ever growing buffer).
So here I gave a go to [bytesToWrite()](https://doc.qt.io/qt-5/qserialport.html#bytesToWrite) and it works pretty well. I tried 9600bauds @ 30 fps with 60 leds, the lag was minimal (compared to no skipping), at the cost of visual frame rate, which remained constant so it's not jarring.
This should also help people who have baudrate/framerate ratio slightly over the optimal value, where they would start seeing the lag 1h later, it should keep them in-sync with few dropped frames.
I implemented a _last will_ with a timer so the very last frame is not …

adalight/ardulight led devices: skip writing frames to serial when buffer is full

---

Software/build-vars.prf.default
Software/grab/GrabberBase.cpp
Software/grab/calculations.cpp
Software/grab/grab.pro
Software/grab/include/calculations.hpp
Software/tests/GrabCalculationTest.cpp

a more efficient way for doing color averaging with better vectorisation
by default this uses SSE4.1 (4 pixel steps), and when available upgrades to AVX2 (8 pixel steps)
this is relatively old tech, and if [Steam Hardware survey](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam) is to believe their availability is decent (98 and 74% respectively) and growing
since the linux version captures at full scale I used it as the main test platform:
- in isolated microbenching AVX2 was almost twice as fast as the old method, SSE a close second
- in Prismatik, depending on profile/build the decrease in CPU usage was around 10-35% (and at the same time with higher reported FPS when grab interval was set to 1ms)
- in my case clang gave the best results, closely …

SIMD color averaging

---

Software/grab/X11Grabber.cpp

this one, I don't know...
while looking around for x11/sync related issues I saw several screen capture samples and they all had these:
- `AllPlanes` instead of a custom `0x00ffffff` mask
- call to `XSync` right after `XShmAttach`
for example in Chromium
https://chromium.googlesource.com/chromium/src/media/+/41a1dc24d5c38474a287a05ab0a8296c71a1cce3/video/capture/screen/x11/x_server_pixel_buffer.cc#138
and
https://chromium.googlesource.com/chromium/src/media/+/41a1dc24d5c38474a287a05ab0a8296c71a1cce3/video/capture/screen/x11/x_server_pixel_buffer.cc#209
So I assume this is _da wae_ to do it. (the documentation leaves a lot to be desired)
Now, this does not fix the weird capture thing from #320 and #325 , but on my VM this hugely reduces Xorg CPU usage (Prismatik unchanged): 10ms grab, 25% …

x11 grabber tweak

---

Software/src/wizard/CustomDistributor.cpp
Software/src/wizard/CustomDistributor.hpp
Software/src/wizard/ZonePlacementPage.cpp

The objective here is to make widgets more even:
- when a side isn't a multiple of LEDs, the leftover space was put into the middle LED, making it (sometimes considerably) larger than the others, so I took that space and redistributed it between middle widgets (1px per)
- the presets (Andromeda etc) can have big differences in sizes between horizontal and vertical LEDs, I made them closer
- Andromeda is using `STAND_WIDTH` (`0.33`) for math and then passes `0.5` to the distributor, changed that
- presets are now updating "custom" fields
- custom config is not using the "stand width" value with odd bottom number
_Andromeda before / after_
_Cassiopeia before / after_
_Pegasus before / after_
_Custom even bottom before / after_
_Custom odd bottom before / after_

widget wizard improvement

---

Software/grab/GrabberBase.cpp
Software/grab/calculations.cpp

fixes #319, the SIMD PR allows this with low cost
"summer teeth" before
after
actually in this particular configuration there are no skipped LEDs, but that's what happens with denser setups

grabberbase: don't trim preparedRect width to multiple of 4

---

Software/grab/WinUtils.cpp
Software/grab/include/WinUtils.hpp

Reload the gamma ramp every 15 seconds to slow memory leak

---

Software/src/LightpackApplication.cpp
Software/src/LightpackApplication.hpp

nogui crash

---

Software/grab/grab.pro
Software/src/src.pro

Not doing so can result in problems during build, see https://bugs.archlinux.org/task/26435
Just for the record, without this patch it resulted in the following [namcap](https://wiki.archlinux.org/index.php/Namcap) warnings on Arch Linux:
* ELF file ('usr/bin/prismatik') lacks FULL RELRO, check LDFLAGS
* Unused shared library '/usr/lib/libGL.so.1'

Respect host linker variables

---

Software/src/LedDeviceManager.cpp

After some changes `break` statements were lost in the `switch`.

Fix LED device creation

---

Software/src/AbstractLedDeviceUdp.hpp
Software/src/LedDeviceDnrgb.cpp
Software/src/LedDeviceDnrgb.hpp

so right now for simplicity sake DNRGB is sending every LED every frame (like DRGB)
the protocol allows for sending only the differences from last frame, so this does that

DNRGB split/diff packets

---

README.md
Software/res/LightpackResources.qrc
Software/res/plugin-template.ini
Software/src/Plugin.cpp
Software/src/Plugin.hpp
Software/src/PluginsManager.cpp

This should fix #396 (works for me™)
while I was there:
- some small improvements to the parsing of the `.ini` (exec args parsing could be better though, but can be worked around)
- added a documented template for the said `.ini`
- added plugin output (and some other info) to the logs

plugins fix/logs

---

Software/src/AbstractLedDevice.cpp
Software/src/AbstractLedDevice.hpp
Software/src/LedDeviceManager.cpp
Software/src/LedDeviceManager.hpp
Software/src/LightpackApplication.cpp
Software/src/Settings.cpp
Software/src/Settings.hpp
Software/src/SettingsDefaults.hpp
Software/src/SettingsWindow.cpp
Software/src/SettingsWindow.hpp
Software/src/SettingsWindow.ui
Software/src/enums.hpp

Fixes #398 by disabling dithering by default. The option exists in device settings now.

Add a setting for dithering, default false.

---

Software/src/AbstractLedDevice.cpp
Software/src/AbstractLedDevice.hpp
Software/src/AbstractLedDeviceUdp.cpp
Software/src/AbstractLedDeviceUdp.hpp
Software/src/LedDeviceDnrgb.cpp
Software/src/LedDeviceDnrgb.hpp
Software/src/LedDeviceDrgb.cpp
Software/src/LedDeviceDrgb.hpp
Software/src/LedDeviceWarls.cpp
Software/src/LedDeviceWarls.hpp

in UDP refactor I made `switchOffLeds()` use `setColors()` which resulted in OFF-frames getting altered by filters #472

udp led devices: allow bypassing color modifications

---

Software/src/AbstractLedDeviceUdp.cpp
Software/src/LedDeviceAdalight.cpp
Software/src/LedDeviceArdulight.cpp

This should trigger the recovery mechanics in LedDeviceManager (#331)

Send ioDeviceSuccess from non-Lightpack devices

---

.github/workflows/ci.yml

it seems to lead to the runner running out of disk space (satackey/action-docker-layer-caching/issues/78)

Skip action-docker-layer-caching on Ubuntu 20.04

---

Software/dist_linux/flatpak/launch_prismatik.sh
Software/dist_linux/flatpak/manifest.yml.template

This PR fixes #541 
Changes done:
1. Put the app icon and .desktop file to the standard paths according to https://docs.flatpak.org/en/latest/conventions.html
2. Add and use a wrapper script to launch Prismatik. The wrapper script basically launches Prismatik with all arguments passed through. However, if `--config-dir` is not defined, use `$XDG_CONFIG_HOME/prismatik` with reference to https://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories
3. No need to export `~/.prismatik` as the configuration is now placed in the flatpak-specific directory as controlled by the wrapper script by default. If user still wants to use `~/.prismatik` or other non-standard directory, they need to allow the flatpak to access those directory manually by `flatpak override` or using Flatseal

Fix issues regarding the Linux flatpak package

---

Software/src/GrabManager.cpp
Software/src/LedDeviceLightpack.cpp
Software/src/LedDeviceLightpack.hpp
Software/src/LedDeviceManager.cpp
Software/src/hidapi/windows/hid.c

The mechanics to stop grabbing on device error may not correctly detect some transient errors, resulting in frozen screen grabbing without a real reason.

Stops grabbing
